# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  extra_module_url:
    #- /www/community/custom-sidebar/custom-sidebar-yaml.js
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml

homeassistant:
  packages: !include_dir_named packages

# button card in HACS
#resources:
#  url: /hacsfiles/simple-thermostat/simple-thermostat.js
#  type: module
#  - url: /hacsfiles/button-card/button-card.js
#    type: module

# ---->>>> HVAC Infinitive MQTT<<<<----
climate:
  - platform: climate_template
    name: Hall Master
    unique_id: dd8a6da3-3eac-4f22-8b81-734f1eb97efe
    modes:
      - "off"
      - heat_cool
      - cool
      - heat
      - dry

    fan_modes:
      - auto
      - low
      - medium
      - high
    min_temp: 59
    max_temp: 81
    target_temperature_high_template: 80
    target_temperature_low_template: 60

    current_temperature_template: "{{ states('sensor.hvacc_hall_east_temp') }}"
    current_humidity_template: "{{ states('sensor.hall_east_indoor_humidity') }}"

    set_hvac_mode:
      - condition: not
        conditions:
          - condition: state
            entity_id: climate.hall_master
            state: "dry" # dry is used as "reset"
      - variables:
          hall_mode: "{{ states('climate.hall_master') }}"
      - service: climate.set_hvac_mode
        data:
          entity_id:
            - climate.hall_east
            - climate.hall_middle
            - climate.hall_west
          hvac_mode: "{{ 'off' if hall_mode == 'dry' else hall_mode if hall_mode != 'heat_cool' else 'auto' }}" #if slaves ever turn off dry -> reset probably isnt working
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.hall_master
          hvac_mode: "dry"

    set_temperature:
      - variables:
          hall_temp: "{{ state_attr('climate.hall_master', 'temperature') | int(0) }}"
          hall_temp_low: "{{ state_attr('climate.hall_master', 'target_temp_low') | int(0) }}"
          hall_temp_high: "{{ state_attr('climate.hall_master', 'target_temp_high') | int(0) }}"
          hall_mode: "{{ states('climate.hall_master') }}"
          eco_low: "{{ states('input_number.hvacc_eco_low') }}"
          eco_hi: "{{ states('input_number.hvacc_eco_hi') }}"
      - service: climate.set_temperature
        data:
          entity_id:
            - climate.hall_east
            - climate.hall_middle
            - climate.hall_west
          target_temp_high: "{{ hall_temp if hall_mode == 'cool' else hall_temp_high if hall_mode == 'heat_cool' else eco_hi }}"
          target_temp_low: "{{ hall_temp if hall_mode == 'heat' else hall_temp_low if hall_mode == 'heat_cool' else eco_low }}"
      - service: climate.set_temperature
        data:
          entity_id:
            - climate.hall_master
          temperature: "{{ 81 if hall_mode == 'cool' else 59 if hall_mode == 'heat' else 68}}"
          target_temp_high: 81
          target_temp_low: 59

    set_fan_mode:
      - service: climate.set_fan_mode
        data:
          entity_id:
            - climate.hall_east
            - climate.hall_middle
            - climate.hall_west
          fan_mode: "{{ state_attr('climate.hall_master', 'fan_mode') }}"

  - platform: climate_template
    name: San
    unique_id: 5222c022-3ee4-419d-afb7-4b42471bc3d7
    modes:
      - "off"
      - heat_cool
      - cool
      - heat
    fan_modes:
      - auto
      - low
      - medium
      - high
    min_temp: 59
    max_temp: 81
    target_temperature_high_template: 80
    target_temperature_low_template: 60
    #target_temperature_template: "{{ state_attr('climate.hall_east', 'temperature') | int(0) }}"
    current_temperature_template: "{{ states('sensor.hvacc_hall_east_temp') }}"
    current_humidity_template: "{{ states('sensor.hall_east_indoor_humidity') }}"

    set_hvac_mode:
      #- variables:
      #   san_mode: "{{ states('climate.sanctuarywest') }}"
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.hall_east
          hvac_mode: "{{ states('climate.san') }}"
          #hvac_mode: "{{ hall_mode if hall_mode != 'heat_cool' else 'auto' }}"

    set_temperature:
      - variables:
          hall_temp: "{{ state_attr('climate.sanctuarywest', 'temperature') | int(0) }}"
          hall_temp_low: "{{ state_attr('climate.sanctuarywest', 'target_temp_low') | int(0) }}"
          hall_temp_high: "{{ state_attr('climate.sanctuarywst', 'target_temp_high') | int(0) }}"
          hall_mode: "{{ states('climate.sanctuarywest') }}"
          eco_low: "{{ states('input_number.hvacc_eco_low') }}"
          eco_hi: "{{ states('input_number.hvacc_eco_hi') }}"
      - service: climate.set_temperature
        data:
          entity_id: climate.hall_east
          target_temp_high: "{{ hall_temp if hall_mode == 'cool' else hall_temp_high if hall_mode == 'heat_cool' else eco_hi }}"
          target_temp_low: "{{ hall_temp if hall_mode == 'heat' else hall_temp_low if hall_mode == 'heat_cool' else eco_low }}"

    set_fan_mode:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hall_east
          fan_mode: "{{ state_attr('climate.sanctuarywest', 'fan_mode') }}"

# config for HVAC run time
# credit: https://blog.stefandroid.com/2022/11/12/home-assistant-track-heating-cooling.html#:~:text=Home%20Assistant%20doesn%27t%20provide,template%20sensor%20and%20history%20statistics.
#https://www.reddit.com/r/homeassistant/comments/199bgvy/hvac_runtime_history_stats_is_there_a_better_more/

# Sensor to track HVAC cooling time using history_stats
template:
  - sensor:
      - name: "HVACc Hall West Action"
        state: "{{ state_attr('climate.hall_west', 'hvac_action') }}"
      - name: "HVACc Hall Middle Action"
        state: "{{ state_attr('climate.hall_middle', 'hvac_action') }}"
      - name: "HVACc Hall East Action"
        state: "{{ state_attr('climate.hall_east', 'hvac_action') }}"
      #      - name: "HVACc FHallWest State"
      #        state: "{{ state_attr('climate.infinitive', 'hvac_action') }}"
      #      - name: "HVACc FHallWest Fan"
      #        state: "{{ state_attr('climate.infinitive', 'blower_rpm') }}"
      #      - name: "HVACc FHallWest SetTemp"
      #        state: "{{ state_attr('climate.infinitive', 'temperature') }}"
      #        unit_of_measurement: "째F"
      - name: "HVACc HallWest Temp"
        state: "{{ state_attr('climate.hall_west', 'current_temperature') }}"
        unit_of_measurement: "째F"
      - name: "HVACc HallMiddle Temp"
        #friendly_name: "Hall Middle Temp"
        state: "{{ state_attr('climate.hall_middle', 'current_temperature') }}"
        unit_of_measurement: "째F"
      - name: "HVACc Hall East Temp"
        unique_id: "ea8b2d88-e12b-437e-88c8-b37466d7e498"
        state: "{{ state_attr('climate.hall_east', 'current_temperature') }}"
        unit_of_measurement: "째F"

      ## ---->>>> School <<<<----
      - name: "HVAC Class East State"
        state: "{{ state_attr('climate.class_east', 'hvac_action') }}"
      - name: "HVAC Class Upstairs State"
        state: "{{ state_attr('climate.class_upstairs', 'hvac_action') }}"
sensor:
  - platform: history_stats
    name: "HVACc Hall West Heating Hours Today"
    entity_id: sensor.hvacc_hall_west_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVACc Hall West Cooling Hours Today"
    entity_id: sensor.hvacc_hall_west_action
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVACc Hall Middle Heating Hours Today"
    entity_id: sensor.hvacc_hall_middle_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVACc Hall Middle Cooling Hours Today"
    entity_id: sensor.hvacc_hall_middle_action
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVACc Hall East Heating Hours Today"
    entity_id: sensor.hvacc_hall_east_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVACc Hall East Cooling Hours Today"
    entity_id: sensor.hvacc_hall_east_action
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  ## ---->>>> School <<<<----
  - platform: history_stats
    name: "HVAC Class East Heating Hours Today"
    entity_id: sensor.hvac_class_east_state
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVAC Class East Cooling Hours Today"
    entity_id: sensor.hvac_class_east_state
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    # -->> Upstairs <<--
  - platform: history_stats
    name: "HVAC Class Upstairs Heating Hours Today"
    entity_id: sensor.hvac_class_upstairs_state
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: "HVAC Class Upstairs Cooling Hours Today"
    entity_id: sensor.hvac_class_upstairs_state
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
